# Generated by https://quicktype.io
#
# To change quicktype's target language, run command:
#
#   "Set quicktype target language"

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class Props(BaseModel):
    created: int
    name: str = ""
    description: str | None = None
    ownerId: str | None = Field(default=None, alias="_ownerId")
    metaNodeId: str | None = Field(default=None, alias="_metaNodeId")
    docType: str | None = Field(default=None, alias="_docType")
    sourceId: str | None = Field(default=None, alias="_sourceId")
    view: str | None = None
    editMode: bool | None = False
    done: bool | int | None | None = None


class NodeDump(BaseModel):
    id: str
    props: Props
    touchCounts: list[int] | None = None
    modifiedTs: list[int] | None = None
    children: list[str] | None = None
    associationMap: dict[str, str] | None = None
    underConstruction: bool | None = None
    inbound_refs: list[str] | None = []
    outbound_refs: list[str] | None = []
    color: str | None = None
    tags: list[str] = []
    content: list[str] = []
    fields: list[dict] = []


# config for graph visualization.
# By default, we inlucde all linkages
class Visualizer(BaseModel):
    include_tag_tag_links: bool = True
    include_node_tag_links: bool = True
    include_inline_refs: bool = True
    include_inline_ref_nodes: bool = True
    include_content_nodes: bool = False
    include_tag_schema_links: bool | None = False
    # make this hashable
    model_config = ConfigDict(frozen=True)


class TanaDump(BaseModel):
    formatVersion: int
    docs: list[NodeDump]
    editors: list[list[int | str]]
    workspaces: dict[str, str]
    lastTxid: int | None = None
    lastFbKey: str | None = None
    optimisticTransIds: list[Any] | None = None
    currentWorkspaceId: str | None = None

    visualize: Visualizer | None = None


class TanaField(BaseModel):
    field_id: str
    name: str
    value_id: str
    value: str
    # tag_id: str = ''


class TanaTag(BaseModel):
    id: str
    name: str
    description: str | None = None
    color: str | None = None


class TanaDocument(BaseModel):
    id: str  # the tana node id
    name: str
    description: str | None
    tags: list[str] = []
    fields: list[TanaField] | None
    # TODO: consider whether we should preserve more node structure here
    content: list[tuple[str | None, bool, str]] = []


class GraphLink(BaseModel):
    source: str
    target: str
    reason: str
